version: '3.8'

services :
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: coldtea
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: vdbprofiles
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8082:8080