# application.yml
keycloak:
  auth-server-url: http://localhost:8085/auth
  realm: VerborumUsers
  resource: verborum-users-ms
  credentials:
    secret: Rp0sbJfme7YUrLPaez2YyYtCiuOZebD1
  public-client: false
  bearer-only: true

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: verborum-users-ms
            client-secret: Rp0sbJfme7YUrLPaez2YyYtCiuOZebD1
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/VerborumUsers
            user-name-attribute: preferred_username